name: Tag Only

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Extrair versão do Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version =' gui/Cargo.toml | head -n1 | sed -E 's/.*"(.*)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Criar tag com a versão
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a "v${{ steps.extract_version.outputs.version }}" -m "Release v${{ steps.extract_version.outputs.version }}"
          git push origin "v${{ steps.extract_version.outputs.version }}"