name: Release on Tag

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build GUI
        run: cargo build --release -p ch57x-keyboard-tool-gui --target ${{ matrix.target }}

      - name: Upload GUI binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ch57x-keyboard-tool-gui
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          include: example-mapping.yaml
